In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
in_channels = 1
out_channels = 1
kernel_size = 3
batch_size = 1
bias = False
input_size = [batch_size, in_channels, 4, 4]
conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size, bias=bias)
input_feature_map = torch.randn(input_size)
output_feature_map = conv_layer(input_feature_map)
print(input_feature_map)
print(conv_layer.weight) # 1*1*3*3=out_channels*in_channels*kernel_height*kernel_width
print(output_feature_map)

tensor([[[[ 1.1828, -0.6560, -0.9519,  0.3228],
          [-1.3688, -0.5385, -0.7152,  0.5805],
          [-1.4870, -1.0126,  0.6372,  1.0882],
          [ 0.9330,  0.9369, -0.2037, -1.4090]]]])
Parameter containing:
tensor([[[[-0.0811, -0.0995, -0.0288],
          [-0.2408, -0.3231,  0.1202],
          [ 0.1623,  0.1546,  0.0915]]]], requires_grad=True)
tensor([[[[0.0747, 0.6029],
          [1.2247, 0.2585]]]], grad_fn=<ConvolutionBackward0>)
